#!/usr/bin/env sh

TEMPLATES_DIR="$HOME/Library/Developer/Xcode/Templates"
PROJECT_TEMPLATES_DIR="$TEMPLATES_DIR/Project Templates"
FILE_TEMPLATES_DIR="$TEMPLATES_DIR/File Templates"

REEFISH_TARGET_PROJECT_TEMPLATES_DIR="$PROJECT_TEMPLATES_DIR/ReeFish"
REEFISH_TARGET_FILE_TEMPLATES_DIR="$FILE_TEMPLATES_DIR/ReeFish"

echo "uninstall ReeFish Project templates : $REEFISH_TARGET_PROJECT_TEMPLATES_DIR"
rm -rf "$REEFISH_TARGET_PROJECT_TEMPLATES_DIR"

echo "uninstall ReeFish File templates : $REEFISH_TARGET_FILE_TEMPLATES_DIR"
rm -rf "$REEFISH_TARGET_FILE_TEMPLATES_DIR"

echo "uninstall Finished."
