workspace '___PACKAGENAME___'

target :___PACKAGENAME___ do
    
platform :ios, '7.0'

pod 'AFNetworking', '~> 2.0'
#pod 'JSONKit-NoWarning', '~> 1.2'
#pod 'SDWebImage'
#pod 'MBProgressHUD'
#pod 'libextobjc'

end


